- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variable
    ansible.builtin.debug:
      msg: "Hello {{ PERSON | default('RAMESH') }}"

  - name: list of fruits
    vars:
      fruits: "apple,banana,orange"
    ansible.builtin.debug:
      msg: "Fruits are: {{ fruits | split(',') }}"

  - name: convert map/dict to list
    vars:
      course:
        name: Ansible
        duration: 10Hrs
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"

  - name: convert list to map/dict
    vars:
      course:
      - {'key': 'name', 'value': 'Ansible'}
      - {'key': 'duration', 'value': '10Hrs'}
      - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: "Course info: {{ course | items2dict }}"

  - name: convert upper to lower
    tags:
    - uppertolower
    vars:
      name: "Gurram Sudheer Raja"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"

  - name: convert lower to upper
    vars:
      name: "Gurram Sudheer Raja"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: print min and max
    vars:
      numbers: [ 2, 345,-89, 2345, 5000]
    ansible.builtin.debug:
      msg: "Min is: {{ numbers | min }}, Max is: {{ numbers | max }}"

  - name: check ip address is valid or not
    vars:
      ip: 192.162.5.55
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr }}"

  
