- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variable
    ansible.builtin.debug:
      msg: "Hello {{ PERSON | default('RAMESH') }}"

  - name: list of fruits
    vars:
      fruits: apple,banana,orange
    ansible.builtin.debug:
      msg: "list of fruits: {{ fruits | split(',') }}"