- name: create ec2-user and r53 records
  hosts: local
  connection: local
  vars:
    sg_id: sg-0dc5f63c638a79919 
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    subnet_id: subnet-0cd0fb0938e30a9a4
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: Install AWS Python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore

  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      instance_type: "{{ instance_type }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_info

  # - name: print ec2_info
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_info }}"

  - name: print private IP addressess
    ansible.builtin.debug:
      msg: "{{ tem.item}} ===> {{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_info.results }}"